name: CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy files
      uses: appleboy/scp-action@v0.0.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "./"
        target: "bot/mathobot"
        overwrite: true
        strip_components: 1

  build:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
    - name: Install, build and run project
      uses: appleboy/ssh-action@v0.0.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: cd ~/bot/mathobot && yarn install --force && yarn build && pm2 restart mathobot
